# Generated by Django 2.1.7 on 2019-03-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190322_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Course',
        ),
    ]
